import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import "./globals.css";

const maven_pro = Maven_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <link rel="manifest" href="/manifest.json" />
            <link rel="apple-touch-icon" href="/icon.png"></link>
            <meta name="theme-color" content="#01688D" />
            <body>{children}</body>
        </html>
    );
}
